import checkoutFormModel from './checkoutFormModel';
const {
  formField: {
    departamento,
    municipio,
    corregimiento,
    localidad_comuna,
    barrio_vereda,
    predio_folio_matricula,
    matricula_inmobiliaria_orip,
    numero_matricula_inmobiliaria,
    numero_predial_nuevo_folio,
    numero_predial_anterior_folio,
    calidadDerechoRegistro,
    documento_soporta_derecho,
    numero_documento,
    fecha_documento,
    ente_emisor,
    cabida_linderos,
    tipo_catastro,
    numero_predial,
    numero_predial_anterior,
    circulo_registral,
    matricula_inmobiliaria_catastro,
    direccion,
    tipo_predio,
    destinacion_economica,
    area_terreno_alfanumerica,
    area_terreno_digital,
    torre_n,
    total_pisos_torre,
    total_unidades_sotano,
    total_unidades_privadas,
    total_sotanos,
    area_total_terreno,
    area_total_terreno_privada,
    area_total_terreno_comun,
    area_total_construida,
    area_total_construida_privada,
    area_total_construida_comun,
    clase_suelo,
    predio_matriz_que_nace,
    predios_catastrales_engloban,
    nombre_direccion_predio,
    destinacion_economica_lista,
    documento_soporta_relacion_predio,
    numero_documento2,
    fecha_documento2,
    ente_emisor2,
    observacion,
    recolector_nombre,
    recolector_firma,
    recolector_fecha,
    array,
  }
} = checkoutFormModel;

export default {
  [departamento.name]: '',
  [municipio.name]: '',
  [corregimiento.name]: '',
  [localidad_comuna.name]: '',
  [barrio_vereda.name]: '',
  [predio_folio_matricula.name]: false,
  [matricula_inmobiliaria_orip.name]: '',
  [numero_matricula_inmobiliaria.name]: '',
  [numero_predial_nuevo_folio.name]: '',
  [numero_predial_anterior_folio.name]: '',
  [calidadDerechoRegistro.name]: '',
  [documento_soporta_derecho.name]: '',
  [numero_documento.name]: '',
  [fecha_documento.name]: '',
  [ente_emisor.name]: '',
  [cabida_linderos.name]: '',
  [tipo_catastro.name]: '',
  [numero_predial.name]: '',
  [numero_predial_anterior.name]: '',
  [circulo_registral.name]: '',
  [matricula_inmobiliaria_catastro.name]: '',
  [direccion.name]: '',
  [tipo_predio.name]: '',
  [destinacion_economica.name]: '',
  [area_terreno_alfanumerica.name]: '',
  [area_terreno_digital.name]: '',
  [torre_n.name]: '',
  [total_pisos_torre.name]: '',
  [total_unidades_sotano.name]: '',
  [total_unidades_privadas.name]: '',
  [total_sotanos.name]: '',
  [area_total_terreno.name]: '',
  [area_total_terreno_privada.name]: '',
  [area_total_terreno_comun.name]: '',
  [area_total_construida.name]: '',
  [area_total_construida_privada.name]: '',
  [area_total_construida_comun.name]: '',
  [clase_suelo.name]: '',
  [predio_matriz_que_nace.name]: '',
  [predios_catastrales_engloban.name]: '',
  [nombre_direccion_predio.name]: '',
  [destinacion_economica_lista.name]: '',
  [documento_soporta_relacion_predio.name]: '',
  [numero_documento2.name]: '',
  [fecha_documento2.name]: '',
  [ente_emisor2.name]: '',
  [observacion.name]: '',
  [recolector_nombre.name]: '',
  [recolector_firma.name]: '',
  [recolector_fecha.name]: '',
  [array.name]: []
};
